apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-blockchain
  namespace: blockchain
spec:
  selector:
    matchLabels:
      app: mysql-blockchain
  template:
    metadata:
      labels:
        app: mysql-blockchain
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "juniorzamo1999"
        - name: MYSQL_DATABASE
          value: "msvc-blockchain"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-blockchain
  namespace: blockchain
spec:
  selector:
    app: mysql-blockchain
  ports:
  - port: 3306
    targetPort: 3306
  type: LoadBalancer